- name: Copy Elastic Repo File
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install File Beat
  ansible.builtin.yum:
    name: filebeat
    state: present


- name: Changing Filebeat yum file to send output to logstash
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Enable and start filebeat service
  ansible.builtin.systemd:
    state: restarted
    name: filebeat
    enabled: true