- name: Copy MySQL Repo File
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable Default version
  command: dnf module disable mysql -y

- name: Install Mysql
  dnf:
    name: mysql-community-server
    state: present

- name: Start Mysql service
  ansible.builtin.systemd:
    state: restarted
    name: mysqld
    enabled: true